version: '3.4'

services:
  webapi:
    build:
      context: .
      dockerfile: DockerfileSe
    environment:
      - "ASPNETCORE_URLS=http://+:5001;http://+:5000"
    ports:
      - "5000:5000"
      - "5001:5001"
